import React from "react";
import Select from "react-select";

function Menu({currArtist, setCurrArtist}) {
  const options = [
    { label: "AALIYAH", value: "AAL" },
    { label: "ABBA", value: "ABA" },
    { label: "ADELE", value: "ADE" },
    { label: "ALLIE X", value: "ALX" },
    { label: "ALVVAYS", value: "ALV" },
    { label: "ALY & AJ", value: "AAJ" },
    { label: "AMY WINEHOUSE", value: "AWH" },
    { label: "ANGEL OLSEN", value: "ANG" },
    { label: "ANITTA", value: "ANI" },
    { label: "ARCA", value: "ARC" },
    { label: "ARIANA GRANDE", value: "ARI" },
    { label: "AVA MAX", value: "AVA" },
    { label: "AZEALIA BANKS", value: "AZB" },
    { label: "BAD BUNNY", value: "BAD" },
    { label: "BANKS", value: "BAN" },
    { label: "BEBE REXHA", value: "BEB" },
    { label: "BEYONCÉ", value: "BEY" },
    { label: "BIG THIEF", value: "BIG" },
    { label: "BILLIE EILISH", value: "BIL" },
    { label: "BJÖRK", value: "BJK" },
    { label: "BLACKPINK", value: "BLA" },
    { label: "BLEACHERS", value: "BLE" },
    { label: "BRITNEY SPEARS", value: "BRT" },
    { label: "BROCKHAMPTON", value: "BRK" },
    { label: "BRUNO MARS", value: "BRO" },
    { label: "BTS", value: "BTS" },
    { label: "CALVIN HARRIS", value: "CAL" },
    { label: "CAMILA CABELLO", value: "CAC" },
    { label: "CARDI B", value: "CDB" },
    { label: "CARLY RAE JEPSEN", value: "CRJ" },
    { label: "CAROLINE POLACHEK", value: "CPO" },
    { label: "CARRIE UNDERWOOD", value: "CUW" },
    { label: "CHARLI XCX", value: "XCX" },
    { label: "CHARLIE PUTH", value: "CPU" },
    { label: "CHVRCHES", value: "CHV" },
    { label: "CLAIRO", value: "CLA" },
    { label: "COBRAH", value: "COB" },
    { label: "COLDPLAY", value: "COL" },
    { label: "CONAN GRAY", value: "CON" },
    { label: "DAGNY", value: "DAG" },
    { label: "DAVID BOWIE", value: "DBO" },
    { label: "DEMI LOVATO", value: "DEM" },
    { label: "DESTINY'S CHILD", value: "DES" },
    { label: "DOJA CAT", value: "DOJ" },
    { label: "DRAKE", value: "DRA" },
    { label: "DUA LIPA", value: "DUA" },
    { label: "ED SHEERAN", value: "EDS" },
    { label: "ELLIE GOULDING", value: "ELL" },
    { label: "ELTON JOHN", value: "ELT" },
    { label: "ETHEL CAIN", value: "ETH" },
    { label: "F(X)", value: "FEX" },
    { label: "FIONA APPLE", value: "FIO" },
    { label: "5 SECONDS OF SUMMER", value: "SOS" },
    { label: "FKA TWIGS", value: "FKA" },
    { label: "FLORENCE + THE MACHINE", value: "FLO" },
    { label: "FRANK OCEAN", value: "FRA" },
    { label: "GORILLAZ", value: "GOR" },
    { label: "GRIMES", value: "GRI" },
    { label: "HAIM", value: "HAI" },
    { label: "HALSEY", value: "HAL" },
    { label: "HANNAH DIAMOND", value: "HAN" },
    { label: "HARRY STYLES", value: "HAR" },
    { label: "IGGY AZALEA", value: "IGG" },
    { label: "IMAGINE DRAGONS", value: "IMD" },
    { label: "ITZY", value: "ITZ" },
    { label: "JANELLE MONÁE", value: "JNM" },
    { label: "JANET JACKSON", value: "JJK" },
    { label: "JHENÉ AIKO", value: "JHE" },
    { label: "JOJI", value: "JOJ" },
    { label: "JULIA MICHAELS", value: "JUL" },
    { label: "JUSTIN BIEBER", value: "JUB" },
    { label: "KACEY MUSGRAVES", value: "KCM" },
    { label: "KALI UCHIS", value: "KAL" },
    { label: "KANYE WEST", value: "KYE" },
    { label: "KATE BUSH", value: "KBU" },
    { label: "KATY PERRY", value: "KPY" },
    { label: "KELLY CLARKSON", value: "KCK" },
    { label: "KENDRICK LAMAR", value: "KEN" },
    { label: "KERO KERO BONITO", value: "KKB" },
    { label: "KESHA", value: "KSH" },
    { label: "KHALID", value: "KHA" },
    { label: "KIM PETRAS", value: "KIM" },
    { label: "KIMBRA", value: "KMB" },
    { label: "KYLIE MINOGUE", value: "KYL" },
    { label: "LADY GAGA", value: "LGA" },
    { label: "LANA DEL REY", value: "LDR" },
    { label: "LIGHTS", value: "LIG" },
    { label: "LIL NAS X", value: "LNX" },
    { label: "LITTLE MIX", value: "LMX" },
    { label: "LIZZO", value: "LZO" },
    { label: "LORDE", value: "LOR" },
    { label: "MADONNA", value: "MAD" },
    { label: "MAGDALENA BAY", value: "MAG" },
    { label: "MAGGIE ROGERS", value: "MRO" },
    { label: "MARIAH CAREY", value: "MCA" },
    { label: "MARINA", value: "MAR" },
    { label: "MAROON 5", value: "MOO" },
    { label: "MEGAN THEE STALLION", value: "MTS" },
    { label: "MEGHAN TRAINOR", value: "MEG" },
    { label: "MIA", value: "MIA" },
    { label: "MICHAEL JACKSON", value: "MJC" },
    { label: "MILEY CYRUS", value: "MIL" },
    { label: "MITSKI", value: "MSK" },
    { label: "MØ", value: "MOE" },
    { label: "MOTHICA", value: "MTH" },
    { label: "MUNA", value: "MUN" },
    { label: "NICKI MINAJ", value: "NIK" },
    { label: "OLIVIA RODRIGO", value: "OLI" },
    { label: "ONE DIRECTION", value: "ODR" },
    { label: "P!NK", value: "PNK" },
    { label: "PANIC! AT THE DISCO", value: "PAN" },
    { label: "PARAMORE", value: "PAR" },
    { label: "PHOEBE BRIDGERS", value: "PHO" },
    { label: "PITBULL", value: "PIT" },
    { label: "POPPY", value: "POP" },
    { label: "PRINCE", value: "PRI" },
    { label: "REGINA SPEKTOR", value: "REG" },
    { label: "RIHANNA", value: "RIH" },
    { label: "RINA SAWAYAMA", value: "RIN" },
    { label: "ROSALÍA", value: "ROS" },
    { label: "SABRINA CARPENTER", value: "SAB" },
    { label: "SHAKIRA", value: "SHA" },
    { label: "SHAWN MENDES", value: "SHM" },
    { label: "SHYGIRL", value: "SHY" },
    { label: "SIA", value: "SIA" },
    { label: "SKY FERREIRA", value: "SKY" },
    { label: "SNAIL MAIL", value: "SNM" },
    { label: "SOCCER MOMMY", value: "SCM" },
    { label: "SOLANGE", value: "SOL" },
    { label: "SOPHIE", value: "SOP" },
    { label: "SOPHIE ELLIS-BEXTOR", value: "SEB" },
    { label: "STROMAE", value: "SRM" },
    { label: "SUFJAN STEVENS", value: "SUF" },
    { label: "SZA", value: "SZA" },
    { label: "TAYLOR SWIFT", value: "TSW" },
    { label: "TEGAN AND SARA", value: "TAS" },
    { label: "THE 1975", value: "THE" },
    { label: "THE BEATLES", value: "BTL" },
    { label: "THE CHAINSMOKERS", value: "CSK" },
    { label: "THE KILLERS", value: "KIL" },
    { label: "THE WEEKND", value: "WKD" },
    { label: "TINASHE", value: "TIN" },
    { label: "TLC", value: "TLC" },
    { label: "TOVE LO", value: "TOV" },
    { label: "TROYE SIVAN", value: "TRY" },
    { label: "TYLER, THE CREATOR", value: "TYC" },
    { label: "WHITNEY HOUSTON", value: "WHI" },
    { label: "WILLOW", value: "WIL" },
    { label: "ZARA LARSSON", value: "ZAR" },
  ]

  function handleChange(event) { // whole object of selected option 
    setCurrArtist(event.value);
  };

  return (
    <section id="artist-selector">
      <Select 
        options={options}
        value={options.find(obj => obj.value === currArtist)}
        onChange={handleChange}
      />
    </section>
  )
}
export default Menu;